AWSTemplateFormatVersion: '2010-09-09'
Description: (SO9100) CrossRegion Failover Graceful Failback and Observability v1

Parameters:
  SourceRegion:
    Type: String
  GlobalClusterIdentifier:
    Type: String
  ClusterName:
    Type: String
  DatabaseName:
    Type: String
  MachineType:
    Default: db.r4.large
    Type: String
    AllowedValues:
      - db.r4.large
      - db.r5.large
  EngineFamily:
    Default: 'aurora-postgresql11'
    Type: String
  PostgresVersion:
    Default: '11.9'
    Type: String
  PostgresEngineMode:
    Default: 'provisioned'
    Type: String
    AllowedValues:
      - 'global'
      - 'provisioned'
Resources:

  DBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Family: !Ref EngineFamily
      Parameters:
        max_connections: 300
      Description: DBClusterParameterGroup

  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Family: !Ref EngineFamily
      Parameters:
        max_connections: 300
      Description: DBParameterGroup

  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Id: key-aurora
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Join
                - ''
                - - 'arn:aws:iam::'
                  - !Ref 'AWS::AccountId'
                  - ':root'
            Action: 'kms:*'
            Resource: '*'

  KMSAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/aurora
      TargetKeyId:
        Ref: KMSKey

  DBCluster:
    DependsOn:
      - DBClusterParameterGroup
      - SubnetGroup
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: !Ref ClusterName
      DBClusterParameterGroupName: !Ref DBClusterParameterGroup
      DBSubnetGroupName: !Ref SubnetGroup
      DeletionProtection: false
      Engine: aurora-postgresql
      EngineVersion: !Ref PostgresVersion
      EngineMode: !Ref PostgresEngineMode
      GlobalClusterIdentifier: !Ref GlobalClusterIdentifier
      Port: '5432'
      StorageEncrypted: true
      KmsKeyId: !Ref KMSKey
      SourceRegion: !Ref SourceRegion
      VpcSecurityGroupIds:
        - '{{resolve:ssm:/crf/aurora-security-group}}'

  DBInstance2:
    DependsOn:
      - DBParameterGroup
      - DBCluster
      - SubnetGroup
    Type: AWS::RDS::DBInstance
    Properties:
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceIdentifier: !Sub '${ClusterName}-instance2'
      DBInstanceClass: !Ref MachineType
      DBParameterGroupName: !Ref DBParameterGroup
      DBSubnetGroupName: !Ref SubnetGroup
      Engine: aurora-postgresql
      EngineVersion: !Ref PostgresVersion
      PubliclyAccessible: false

  SubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      SubnetIds:
        - '{{resolve:secretsmanager:vpc2-private-subnet-1}}'
        - '{{resolve:secretsmanager:vpc2-private-subnet-2}}'
        - '{{resolve:secretsmanager:vpc2-private-subnet-3}}'
      DBSubnetGroupDescription: !Sub ${DatabaseName}-subnet-group

Outputs:
  DBEndpoint:
    Value: !GetAtt DBCluster.Endpoint.Address
    Export:
      Name: !Sub "${AWS::StackName}-DBEndpoint"
  DBPort:
    Value: !GetAtt DBCluster.Endpoint.Port
    Export:
      Name: !Sub "${AWS::StackName}-DBPort"