AWSTemplateFormatVersion: '2010-09-09'
Description: (SO9099) CrossRegion Failover Graceful Failback and Observability v1

Parameters:

  BucketName:
    Type: String
    Description: The bucket name
  RegionName:
    Type: String
    Description: The bucket name
  BackupRegion:
    Type: String
    Description: The bucket name

Resources:

  Bucket:
    Type: 'AWS::S3::Bucket'
    DependsOn:
      - LoggingBucket
    Metadata:
      Comment: 'The cloud front bucket'
    DeletionPolicy: 'Delete'
    Properties:
      AccessControl: 'Private'
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: bucket-logs/

  LoggingBucket:
    Type: 'AWS::S3::Bucket'
    Metadata:
      Comment: 'The logging bucket'
    DeletionPolicy: 'Delete'
    Properties:
      AccessControl: LogDeliveryWrite
      BucketName: !Sub
        - ${BucketName}-log
        - BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  BucketNameSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: !Sub "cloudfront-${RegionName}-bucket-name"
      Description: !Sub "cloudfront-${RegionName}-bucket-name"
      KmsKeyId: "alias/aws/secretsmanager"
      ReplicaRegions:
        - Region: !Ref BackupRegion
          KmsKeyId: "alias/aws/secretsmanager"
      SecretString: !Ref Bucket

  BucketDomainNameSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: !Sub "cloudfront-${RegionName}-bucket-domain-name"
      Description: !Sub "cloudfront-${RegionName}-bucket-domain-name"
      KmsKeyId: "alias/aws/secretsmanager"
      ReplicaRegions:
        - Region: !Ref BackupRegion
          KmsKeyId: "alias/aws/secretsmanager"
      SecretString: !GetAtt Bucket.DomainName

Outputs:

  Name:
    Description: 'The bucket name'
    Value: !Ref Bucket

  Arn:
    Description: 'The bucket ARN'
    Value: !GetAtt Bucket.Arn

  DomainName:
    Description: 'The bucket domain name'
    Value: !GetAtt Bucket.DomainName

  DualStackDomainName:
    Description: 'The bucket dual stack domain name'
    Value: !GetAtt Bucket.DualStackDomainName

  RegionalDomainName:
    Description: 'The bucket regional domain name'
    Value: !GetAtt Bucket.RegionalDomainName

  WebsiteURL:
    Description: 'The bucket website URL'
    Value: !GetAtt Bucket.WebsiteURL