AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template IAM Roles for Systems Manager | Automation Service

Resources:

  AutomationServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ssm.amazonaws.com
            - ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonSSMAutomationRole
      Path: "/"
      RoleName: AutomationServiceRole
      Policies:
      - PolicyName: passrole
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - 'iam:PassRole'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'rds:*'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'secretsmanager:*'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'route53-recovery-control-config:*'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'route53-recovery-cluster:*'
            Resource: '*'
